/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    "index",
    {
      type: "category",
      label: "Getting Started",
      items: [
        "mint/overview",
        "mint/routes",
        "mint/pages",
        "mint/authentication",
      ],
    },
    {
      type: "category",
      label: "Core",
      items: [
        {
          type: "autogenerated",
          dirName: "mint/core",
        },
      ],
    },
  ],
  atomic: [
    "atomic/intro",
    {
      type: "category",
      label: "Features",
      items: [
        "atomic/configurations",
        "atomic/authentication",
        "atomic/helpers",
        "atomic/audit",
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic/api",
        },
      ],
    },
  ],
  atomicAngular: [
    "atomic-angular/intro",
    {
      type: "category",
      label: "Assistant",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/assistant",
        },
      ],
    },
    {
      type: "category",
      label: "Components",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/components",
        },
      ],
    },
    {
      type: "category",
      label: "Directives",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/directives",
        },
      ],
    },
    {
      type: "category",
      label: "Guards",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/guards",
        },
      ],
    },
    {
      type: "category",
      label: "Interceptors",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/interceptors",
        },
      ],
    },
    {
      type: "category",
      label: "Pipes",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/pipes",
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Providers",
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "atomic-angular/providers",
    //     },
    //   ],
    // },
    {
      type: "category",
      label: "Resolvers",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/resolvers",
        },
      ],
    },
    {
      type: "category",
      label: "Services",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/services",
        },
      ],
    },
    {
      type: "category",
      label: "Stores",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/stores",
        },
      ],
    },
    {
      type: "category",
      label: "Tokens",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/tokens",
        },
      ],
    },
    {
      type: "category",
      label: "Utils",
      items: [
        {
          type: "autogenerated",
          dirName: "atomic-angular/utils",
        },
      ],
    },
    "atomic-angular/theme"
  ],
};

export default sidebars;
