# Runs the build process on the 1st and 15th of each month after
# completion of the automated release branch creation script
name: Automated Build Trigger
run-name: ${{ github.actor }} release build ${{ github.repository }}

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  generate-build:
    runs-on: [self-hosted,wps-build]
    steps:
      - name: Get Current Date
        run: |
          Add-Content -Path ${env:GITHUB_ENV} -Value "RELEASE_DATE=$(date -Format 'yyyyMMdd')"
      - name: Checkout Release Branch
        uses: actions/checkout@v3
        with:
          ref: release-${{ env.RELEASE_DATE }}
      - name: Git Configuration
        run: |
          git config --global user.email "jeffery.white@sinequa.com"
          git config --global user.name "Jeffery White"
      - name: Modify Gitignore For Release
        run: |
          ((Get-Content -Path .\.gitignore -Raw) -replace '/dist','') | Set-Content -Path .\.gitignore
          ((Add-Content -Path .\.gitignore "`n.npmrc"))
          ((Add-Content -Path .\.gitignore "`nnpmrc.dl"))
          git add .
          git commit -m 'Build Process GitIgnore Update'
      - name: Run Powershell
        run: |
          .\scripts\get-npmrc.ps1
      - name: Install Packages
        run: |
          npm install
      - name: Build Application
        run: |
          ng build
      - name: Get Github Secret
        run: |
          Connect-AzAccount -Identity
          $token = Get-AzKeyVaultSecret -VaultName 'github-runner-sce-kv' -Name 'sce-build-github-token' -AsPlainText
          echo "CI_TOKEN=$token" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ env.CI_TOKEN }}
          commit-message: Build Commit
          committer: Build Automation <${{ github.actor }}@sinequa.com>
          author: ${{ github.actor }} <${{ github.actor }}@sinequa.com>
          base: release-${{ env.RELEASE_DATE }}
          branch: build-${{ env.RELEASE_DATE }}
          reviewers: loic-juillet
          title: 'Workplace Search Mint Application Build ${{ env.RELEASE_DATE }}'
          body: |
            Automated Build for Workplace Search Mint build-${{ env.RELEASE_DATE }} is awaiting merge to release-${{ env.RELEASE_DATE }}  
