# Creates a new release branch on the 1st and 15th of the month.
name: Automated Release Trigger
run-name: ${{ github.actor }} release ${{ github.repository }}

on:
  schedule:
  - cron: "15 00 * * *"

jobs:
  generate-release:
    runs-on: [self-hosted,wps-build]
    steps:
      - name: Get Current Date (Windows)
        if: runner.os == 'Windows'
        run: |
          Add-Content -Path ${env:GITHUB_ENV} -Value "RELEASE_DATE=$(date -Format 'yyyyMMdd')"
      - name: Get Current Date (Linux)
        if: runner.os == 'Linux' 
        run: |
          echo "RELEASE_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Create Branch
        run: |
          git checkout -b release-${{ env.RELEASE_DATE }}
      - name: Publish Branch
        run: |
          git push --set-upstream origin release-${{ env.RELEASE_DATE }}
      - name: Notify Slack on Success
        if: success()
        run: |
          $repoUrl = "https://github.sinequa.com/${{ github.repository }}/tree/release-${{ env.RELEASE_DATE }}"
          $branchName = "release-${{ env.RELEASE_DATE }}"
          $message = "[${{ github.repository }}] A new release branch has been created!\n<$repoUrl|$branchName>"
          Invoke-WebRequest -Uri 'https://hooks.slack.com/services/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' -Method POST -ContentType 'application/json' -Body "{`"text`":`"$message`"}"      
      - name: Notify Slack on Failure
        if: failure()
        run: |
          $repoUrl = "https://github.sinequa.com/${{ github.repository }}"
          $branchName = "release-${{ env.RELEASE_DATE }}"
          $message = "[${{ github.repository }}] Creation of branch `$branchName` failed to execute\n<$repoUrl|$branchName>"
          Invoke-WebRequest -Uri 'https://hooks.slack.com/services/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' -Method POST -ContentType 'application/json' -Body "{`"text`":`"$message`"}"

